### ISSUE TITLE
Unable to use this plugin on iOS

### ISSUE THREAD

**Issue by njovy** [LBSTECH/naver_map_plugin#4]
I was able to use this plugin on Android but couldn't build on iOS.
I am using Flutter SDK 1.22.2 and XCode 12.

1. Create a new flutter project
2. Import this plugin by adding ```naver_map_plugin``` in pubspec.yaml
3. Below is a log.

```
    [!] The 'Pods-Runner' target has transitive dependencies that include statically linked binaries: (/Users/dev/Developer/flutter/flutterpad/ios/Pods/NMapsMap/framework/NMapsMap.framework)

          /Users/dev/.rvm/gems/ruby-2.7.0-preview1/gems/cocoapods-1.9.3/lib/cocoapods/installer/xcode/target_validator.rb:84:in `block (2 levels) in verify_no_static_framework_transitive_dependencies'
          /Users/dev/.rvm/gems/ruby-2.7.0-preview1/gems/cocoapods-1.9.3/lib/cocoapods/installer/xcode/target_validator.rb:74:in `each_key'
          /Users/dev/.rvm/gems/ruby-2.7.0-preview1/gems/cocoapods-1.9.3/lib/cocoapods/installer/xcode/target_validator.rb:74:in `block in verify_no_static_framework_transitive_dependencies'
          /Users/dev/.rvm/gems/ruby-2.7.0-preview1/gems/cocoapods-1.9.3/lib/cocoapods/installer/xcode/target_validator.rb:73:in `each'
          /Users/dev/.rvm/gems/ruby-2.7.0-preview1/gems/cocoapods-1.9.3/lib/cocoapods/installer/xcode/target_validator.rb:73:in `verify_no_static_framework_transitive_dependencies'
          /Users/dev/.rvm/gems/ruby-2.7.0-preview1/gems/cocoapods-1.9.3/lib/cocoapods/installer/xcode/target_validator.rb:38:in `validate!'
          /Users/dev/.rvm/gems/ruby-2.7.0-preview1/gems/cocoapods-1.9.3/lib/cocoapods/installer.rb:590:in `validate_targets'
          /Users/dev/.rvm/gems/ruby-2.7.0-preview1/gems/cocoapods-1.9.3/lib/cocoapods/installer.rb:158:in `install!'
          /Users/dev/.rvm/gems/ruby-2.7.0-preview1/gems/cocoapods-1.9.3/lib/cocoapods/command/install.rb:52:in `run'
          /Users/dev/.rvm/rubies/ruby-2.7.0-preview1/lib/ruby/gems/2.7.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
          /Users/dev/.rvm/gems/ruby-2.7.0-preview1/gems/cocoapods-1.9.3/lib/cocoapods/command.rb:52:in `run'
          /Users/dev/.rvm/gems/ruby-2.7.0-preview1/gems/cocoapods-1.9.3/bin/pod:55:in `<top (required)>'
          /Users/dev/.rvm/gems/ruby-2.7.0-preview1/bin/pod:23:in `load'
          /Users/dev/.rvm/gems/ruby-2.7.0-preview1/bin/pod:23:in `<main>'
          /Users/dev/.rvm/gems/ruby-2.7.0-preview1/bin/ruby_executable_hooks:24:in `eval'
          /Users/dev/.rvm/gems/ruby-2.7.0-preview1/bin/ruby_executable_hooks:24:in `<main>'
```

**Comment by sjpark-lbstech** [comment]
정확히 어떤 시나리오에서 에러가 난건가요?
pubspec.yaml에 종속성을 설정하고 readme에 있는 지시사항을 모두 진행하고 생기는 에러인가요?
아니면 지시사항을 모두 진행하지 않은 상태인가요?

**Comment by njovy** [comment]
@sjpark-lbstech iOS에서 사용시 빌드가 되질 않습니다. 해당 플러그인의 podspec 설정도 제대로 안된 것 같구요.

**Comment by DaeHyeonNam** [comment]
@njovy 안녕하세요! 지금 이 문제가 해결이 안되고 있는데 어떻게 해결하셨었는지 알 수 있을까요?

**Comment by sjpark-lbstech** [comment]
Read me에 누락된 부분입니다 .

njovy 님이 기제하신것처럼 터미널에서 flutter프로젝트 내에 ios 폴더로 가신 후
```git-lfs install``` 실행하시면 해당 프로젝트에 git-lfs가 초기화되고 이후 ```pod install``` 진행하시면 됩니다

**Comment by DaeHyeonNam** [comment]
@sjpark-lbstech ㅠㅠ 말씀하신 것을 해보았는데도 안되어서 결국엔 ios폴더를 모두 지우고 flutter create 로 다시 만들어서 해보니 해결되었네요. 감사합니다 👍

**Comment by sjpark-lbstech** [comment]
정확한 이유는 모르겠는데 가끔 cocoapod에서 문제가 발생하는 경우가 있더라구요. 

각 플러그인들의 podspec들을 컨트롤하는 과정에서의 문제인것 같습니다 그럴때는 ```pod cache clean --all``` 하고 다시 ```pod install``` 해보시길 권장드립니다.
